<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Mod_reportes extends CI_Model
{
  public function __construct()
  {
      parent::__construct();
      //Do your magic here
  }

  public function ReporteBusqueda($idjefe, $idcargo, $iddependencia, $idciudad, $idempresa, $anoencuesta, $usuario)
  {
    if($anoencuesta != NULL)
      $CondicionAno = 'AND EBIT.ANOBITACORA = '.$anoencuesta;
    else
      $CondicionAno = '';

    $SqlReporte = "
      SELECT IDUSUARIOS, NOMBRES, USU_CREACION, QUIEN_EVALUA, ANOBITACORA, DESCRIPCIONDEPENDENCIA, DESCRIPCIONCARGO, DESCRIPCIONCIUDAD, NOMBREEMPRESA
      FROM (

          SELECT EUSU.IDUSUARIOS, EUSU.NOMBREUSUARIO||' '||EUSU.APELLIDOUSUARIO NOMBRES, EBIT.USUARIOCREACION USU_CREACION, EBUS.NOMBREUSUARIO||' '||EBUS.APELLIDOUSUARIO QUIEN_EVALUA,
              EBIT.ANOBITACORA, EDEP.DESCRIPCIONDEPENDENCIA, ECAR.DESCRIPCIONCARGO, ECIU.DESCRIPCIONCIUDAD, EEMP.NOMBREEMPRESA  
          FROM EVA_USUARIOS EUSU
              INNER JOIN EVA_BITACORAS EBIT ON EUSU.IDUSUARIOS = EBIT.IDUSUARIOS
              INNER JOIN EVA_USUARIOS EBUS ON EBIT.USUARIOCREACION = EBUS.IDUSUARIOS
              INNER JOIN EVA_DEPENDENCIAS EDEP ON EUSU.IDDEPENDENCIA = EDEP.IDDEPENDENCIA
              INNER JOIN EVA_CARGOS ECAR ON EUSU.IDCARGO = ECAR.IDCARGO
              INNER JOIN EVA_CIUDADES ECIU ON EUSU.IDCIUDAD = ECIU.IDCIUDAD
              INNER JOIN EVA_EMPRESA EEMP ON EUSU.IDEMPRESA = EEMP.IDEMPRESA
          WHERE EBIT.USUARIOCREACION = NVL('$idjefe', EBIT.USUARIOCREACION)  
              AND EDEP.IDDEPENDENCIA = DECODE('$iddependencia', '-1', EDEP.IDDEPENDENCIA, '$iddependencia')
              AND ECAR.IDCARGO = DECODE('$idcargo', '-1', ECAR.IDCARGO, '$idcargo')
              AND ECIU.IDCIUDAD = DECODE('$idciudad', '-1', ECIU.IDCIUDAD, '$idciudad')
              AND EEMP.IDEMPRESA = DECODE('$idempresa', '-1', EEMP.IDEMPRESA, '$idempresa') ".$CondicionAno." 

          UNION 

          SELECT EUSU.IDUSUARIOS, EUSU.NOMBREUSUARIO||' '||EUSU.APELLIDOUSUARIO NOMBRES, EBIT.USUARIOCREACION, EBUS.NOMBREUSUARIO||' '||EBUS.APELLIDOUSUARIO QUIEN_EVALUA,
              EBIT.ANOBITACORA, EDEP.DESCRIPCIONDEPENDENCIA, ECAR.DESCRIPCIONCARGO, ECIU.DESCRIPCIONCIUDAD, EEMP.NOMBREEMPRESA   
          FROM EVA_USUARIOS EUSU
              INNER JOIN EVA_BITACORAS EBIT ON EUSU.IDUSUARIOS = EBIT.IDUSUARIOS
              INNER JOIN EVA_USUARIOS EBUS ON EBIT.USUARIOCREACION = EBUS.IDUSUARIOS
              INNER JOIN EVA_DEPENDENCIAS EDEP ON EUSU.IDDEPENDENCIA = EDEP.IDDEPENDENCIA
              INNER JOIN EVA_CARGOS ECAR ON EUSU.IDCARGO = ECAR.IDCARGO
              INNER JOIN EVA_CIUDADES ECIU ON EUSU.IDCIUDAD = ECIU.IDCIUDAD
              INNER JOIN EVA_EMPRESA EEMP ON EUSU.IDEMPRESA = EEMP.IDEMPRESA
          WHERE EBIT.IDUSUARIOS = NVL('$idjefe', EBIT.IDUSUARIOS) 
              AND EDEP.IDDEPENDENCIA = DECODE('$iddependencia', '-1', EDEP.IDDEPENDENCIA, '$iddependencia')
              AND ECAR.IDCARGO = DECODE('$idcargo', '-1', ECAR.IDCARGO, '$idcargo')
              AND ECIU.IDCIUDAD = DECODE('$idciudad', '-1', ECIU.IDCIUDAD, '$idciudad')
              AND EEMP.IDEMPRESA = DECODE('$idempresa', '-1', EEMP.IDEMPRESA, '$idempresa') ".$CondicionAno." 

          UNION

          SELECT EUSU.IDUSUARIOS, EUSU.NOMBREUSUARIO||' '||EUSU.APELLIDOUSUARIO NOMBRES, 0, '',
              EBIT.ANOBITACORA, EDEP.DESCRIPCIONDEPENDENCIA, ECAR.DESCRIPCIONCARGO, ECIU.DESCRIPCIONCIUDAD, EEMP.NOMBREEMPRESA   
          FROM EVA_USUARIOS EUSU
              LEFT JOIN EVA_BITACORAS EBIT ON EUSU.IDUSUARIOS = EBIT.IDUSUARIOS
              INNER JOIN EVA_DEPENDENCIAS EDEP ON EUSU.IDDEPENDENCIA = EDEP.IDDEPENDENCIA
              INNER JOIN EVA_CARGOS ECAR ON EUSU.IDCARGO = ECAR.IDCARGO
              INNER JOIN EVA_CIUDADES ECIU ON EUSU.IDCIUDAD = ECIU.IDCIUDAD
              INNER JOIN EVA_EMPRESA EEMP ON EUSU.IDEMPRESA = EEMP.IDEMPRESA
          WHERE EUSU.CALIFICAUSUARIO = NVL('$idjefe', EUSU.CALIFICAUSUARIO)
              AND EBIT.ANOBITACORA IS NULL
              AND EDEP.IDDEPENDENCIA = DECODE('$iddependencia', '-1', EDEP.IDDEPENDENCIA, '$iddependencia')
              AND ECAR.IDCARGO = DECODE('$idcargo', '-1', ECAR.IDCARGO, '$idcargo')
              AND ECIU.IDCIUDAD = DECODE('$idciudad', '-1', ECIU.IDCIUDAD, '$idciudad')
              AND EEMP.IDEMPRESA = DECODE('$idempresa', '-1', EEMP.IDEMPRESA, '$idempresa') ".$CondicionAno." 
              
          UNION    
              
          SELECT EUSU.IDUSUARIOS, EUSU.NOMBREUSUARIO||' '||EUSU.APELLIDOUSUARIO NOMBRES, 0, '',
              EBIT.ANOBITACORA, EDEP.DESCRIPCIONDEPENDENCIA, ECAR.DESCRIPCIONCARGO, ECIU.DESCRIPCIONCIUDAD, EEMP.NOMBREEMPRESA   
          FROM EVA_USUARIOS EUSU
              LEFT JOIN EVA_BITACORAS EBIT ON EUSU.IDUSUARIOS = EBIT.IDUSUARIOS
              INNER JOIN EVA_DEPENDENCIAS EDEP ON EUSU.IDDEPENDENCIA = EDEP.IDDEPENDENCIA
              INNER JOIN EVA_CARGOS ECAR ON EUSU.IDCARGO = ECAR.IDCARGO
              INNER JOIN EVA_CIUDADES ECIU ON EUSU.IDCIUDAD = ECIU.IDCIUDAD
              INNER JOIN EVA_EMPRESA EEMP ON EUSU.IDEMPRESA = EEMP.IDEMPRESA
          WHERE EUSU.IDUSUARIOS = NVL('$idjefe', EUSU.IDUSUARIOS)
              AND EBIT.ANOBITACORA IS NULL
              AND EDEP.IDDEPENDENCIA = DECODE('$iddependencia', '-1', EDEP.IDDEPENDENCIA, '$iddependencia')
              AND ECAR.IDCARGO = DECODE('$idcargo', '-1', ECAR.IDCARGO, '$idcargo')
              AND ECIU.IDCIUDAD = DECODE('$idciudad', '-1', ECIU.IDCIUDAD, '$idciudad')
              AND EEMP.IDEMPRESA = DECODE('$idempresa', '-1', EEMP.IDEMPRESA, '$idempresa') ".$CondicionAno." 
      ) ORDER BY 9, 5, 2
      ";

    $Sql_Report_General= $this->db->query($SqlReporte);

    if ($Sql_Report_General->num_rows() > 0)
    {
      return $Sql_Report_General->result(); 
    }     
  }

  public function ReporteExcelEvaluacion($idjefe, $idcargo, $iddependencia, $idciudad, $idempresa, $anoencuesta, $usuario)
  {
    if($anoencuesta != NULL)
      $CondicionAno = 'AND EBIT.ANOBITACORA = '.$anoencuesta;
    else
      $CondicionAno = '';

    $QueryReporteExcel = "
      SELECT NOMBREEMPRESA, DESCRIPCIONCIUDAD, USUARIO, DESCRIPCIONCARGO, FORTALEZASBITACORA, AMEJORARBITACORA, ACCIONESBITACORA
      FROM (
          SELECT EEMP.NOMBREEMPRESA, ECIU.DESCRIPCIONCIUDAD, EUSU.NOMBREUSUARIO||' '||EUSU.APELLIDOUSUARIO USUARIO, ECAR.DESCRIPCIONCARGO, 
              EBIT.FORTALEZASBITACORA, EBIT.AMEJORARBITACORA, EBIT.ACCIONESBITACORA  
          FROM EVA_USUARIOS EUSU
              INNER JOIN EVA_BITACORAS EBIT ON EUSU.IDUSUARIOS = EBIT.IDUSUARIOS
              INNER JOIN EVA_USUARIOS EBUS ON EBIT.USUARIOCREACION = EBUS.IDUSUARIOS
              INNER JOIN EVA_DEPENDENCIAS EDEP ON EUSU.IDDEPENDENCIA = EDEP.IDDEPENDENCIA
              INNER JOIN EVA_CARGOS ECAR ON EUSU.IDCARGO = ECAR.IDCARGO
              INNER JOIN EVA_CIUDADES ECIU ON EUSU.IDCIUDAD = ECIU.IDCIUDAD
              INNER JOIN EVA_EMPRESA EEMP ON EUSU.IDEMPRESA = EEMP.IDEMPRESA
          WHERE EBIT.USUARIOCREACION = NVL('$idjefe', EBIT.USUARIOCREACION)  
              AND EDEP.IDDEPENDENCIA = DECODE('$iddependencia', '-1', EDEP.IDDEPENDENCIA, '$iddependencia')
              AND ECAR.IDCARGO = DECODE('$idcargo', '-1', ECAR.IDCARGO, '$idcargo')
              AND ECIU.IDCIUDAD = DECODE('$idciudad', '-1', ECIU.IDCIUDAD, '$idciudad')
              AND EEMP.IDEMPRESA = DECODE('$idempresa', '-1', EEMP.IDEMPRESA, '$idempresa') ".$CondicionAno." 

          UNION 

          SELECT EEMP.NOMBREEMPRESA, ECIU.DESCRIPCIONCIUDAD, EUSU.NOMBREUSUARIO||' '||EUSU.APELLIDOUSUARIO USUARIO, ECAR.DESCRIPCIONCARGO, 
              EBIT.FORTALEZASBITACORA, EBIT.AMEJORARBITACORA, EBIT.ACCIONESBITACORA
          FROM EVA_USUARIOS EUSU
              INNER JOIN EVA_BITACORAS EBIT ON EUSU.IDUSUARIOS = EBIT.IDUSUARIOS
              INNER JOIN EVA_USUARIOS EBUS ON EBIT.USUARIOCREACION = EBUS.IDUSUARIOS
              INNER JOIN EVA_DEPENDENCIAS EDEP ON EUSU.IDDEPENDENCIA = EDEP.IDDEPENDENCIA
              INNER JOIN EVA_CARGOS ECAR ON EUSU.IDCARGO = ECAR.IDCARGO
              INNER JOIN EVA_CIUDADES ECIU ON EUSU.IDCIUDAD = ECIU.IDCIUDAD
              INNER JOIN EVA_EMPRESA EEMP ON EUSU.IDEMPRESA = EEMP.IDEMPRESA
          WHERE EBIT.IDUSUARIOS = NVL('$idjefe', EBIT.IDUSUARIOS) 
              AND EDEP.IDDEPENDENCIA = DECODE('$iddependencia', '-1', EDEP.IDDEPENDENCIA, '$iddependencia')
              AND ECAR.IDCARGO = DECODE('$idcargo', '-1', ECAR.IDCARGO, '$idcargo')
              AND ECIU.IDCIUDAD = DECODE('$idciudad', '-1', ECIU.IDCIUDAD, '$idciudad')
              AND EEMP.IDEMPRESA = DECODE('$idempresa', '-1', EEMP.IDEMPRESA, '$idempresa')  ".$CondicionAno." 

          UNION

          SELECT EEMP.NOMBREEMPRESA, ECIU.DESCRIPCIONCIUDAD, EUSU.NOMBREUSUARIO||' '||EUSU.APELLIDOUSUARIO USUARIO, ECAR.DESCRIPCIONCARGO,
              EBIT.FORTALEZASBITACORA, EBIT.AMEJORARBITACORA, EBIT.ACCIONESBITACORA 
          FROM EVA_USUARIOS EUSU
              LEFT JOIN EVA_BITACORAS EBIT ON EUSU.IDUSUARIOS = EBIT.IDUSUARIOS
              INNER JOIN EVA_DEPENDENCIAS EDEP ON EUSU.IDDEPENDENCIA = EDEP.IDDEPENDENCIA
              INNER JOIN EVA_CARGOS ECAR ON EUSU.IDCARGO = ECAR.IDCARGO
              INNER JOIN EVA_CIUDADES ECIU ON EUSU.IDCIUDAD = ECIU.IDCIUDAD
              INNER JOIN EVA_EMPRESA EEMP ON EUSU.IDEMPRESA = EEMP.IDEMPRESA
          WHERE EUSU.CALIFICAUSUARIO = NVL('$idjefe', EUSU.CALIFICAUSUARIO)
              AND EBIT.ANOBITACORA IS NOT NULL
              AND EDEP.IDDEPENDENCIA = DECODE('$iddependencia', '-1', EDEP.IDDEPENDENCIA, '$iddependencia')
              AND ECAR.IDCARGO = DECODE('$idcargo', '-1', ECAR.IDCARGO, '$idcargo')
              AND ECIU.IDCIUDAD = DECODE('$idciudad', '-1', ECIU.IDCIUDAD, '$idciudad')
              AND EEMP.IDEMPRESA = DECODE('$idempresa', '-1', EEMP.IDEMPRESA, '$idempresa')  ".$CondicionAno." 
      )
      ORDER BY 1, 2, 3
      "; 
    
    $Sql_Report_Excel= $this->db->query($QueryReporteExcel);

    if ($Sql_Report_Excel->num_rows() > 0)
    {
      return $Sql_Report_Excel->result(); 
    }     
  }
}   